const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const read = (name) => fs.readFileSync(path.join(__dirname, "..", name), "utf8")

test("bar launcher and visible controls have accessible button names", () => {
  const bar = read("BarWidget.qml")
  const overlay = read("Overlay.qml")
  const journey = read("JourneyView.qml")
  const button = read("OmatrailButton.qml")
  assert.match(bar, /Accessible\.role:\s*Accessible\.Button/)
  assert.match(bar, /Accessible\.name:\s*"Open omaTrail"/)
  assert.match(button, /Accessible\.role:\s*Accessible\.Button/)
  assert.match(button, /Accessible\.name:\s*root\.label/)
  assert.match(button, /Accessible\.onPressAction:/)
  assert.ok((overlay.match(/OmatrailButton\s*{/g) || []).length >= 3)
  assert.ok((journey.match(/OmatrailButton\s*{/g) || []).length >= 10)
  assert.match(journey, /Accessible\.name:\s*"Traveler " \+ \(index \+ 1\) \+ " name"/)
})

test("keyboard and mouse cover the complete hunting action set", () => {
  const overlay = read("Overlay.qml")
  const board = read("HuntingBoard.qml")
  for (const key of ["Qt.Key_Escape", "Qt.Key_Enter", "Qt.Key_Space", "Qt.Key_Left", "Qt.Key_Right", "Qt.Key_Up", "Qt.Key_Down"])
    assert.match(overlay, new RegExp(key.replace(".", "\\.")))
  for (const letter of ["w", "a", "s", "d", "p", "h", "q"])
    assert.match(overlay, new RegExp(`key === "${letter}"`))
  assert.match(overlay, /Qt\.Key_V/)
  assert.match(overlay, /Qt\.Key_1[\s\S]*Qt\.Key_5/)
  assert.match(board, /MouseArea\s*{[\s\S]*onClicked:/)
  assert.match(board, /acceptedButtons:\s*Qt\.LeftButton \| Qt\.RightButton/)
  assert.match(board, /mouse\.button === Qt\.RightButton[\s\S]*root\.move\(dx, dy\)/)
  assert.match(board, /root\.aim\(dx, dy\)[\s\S]*root\.fire\(\)/)
})

test("dynamic text is plain, bounded, and does not change simulation timing", () => {
  const overlay = read("Overlay.qml")
  const board = read("HuntingBoard.qml")
  assert.match(overlay, /text:\s*board\.huntState\.message[\s\S]{0,180}textFormat:\s*Text\.PlainText[\s\S]{0,180}elide:/)
  const messageStart = board.indexOf("text: root.huntState.message")
  assert.notEqual(messageStart, -1)
  const messageBlock = board.slice(Math.max(0, messageStart - 140), messageStart + 180)
  assert.match(messageBlock, /width:/)
  assert.match(messageBlock, /wrapMode:\s*Text\.WordWrap/)
  assert.match(messageBlock, /textFormat:\s*Text\.PlainText/)
  assert.match(board, /interval:\s*100/)
  assert.doesNotMatch(board, /interval:\s*root\.reducedMotion/)
  assert.match(board, /NumberAnimation on y[\s\S]*running:\s*scanline\.visible && !root\.reducedMotion/)
  const journey = read("JourneyView.qml")
  assert.match(journey, /property string pendingRiverChoice:\s*""/)
  assert.match(journey, /function confirmRiverChoice\(\)/)
  assert.match(journey, /CONFIRM CROSSING/)
  assert.match(journey, /NumberAnimation on x[\s\S]*!root\.reducedMotion/)
  for (const label of ["DURATION", "SURVIVORS:", "LOSSES:", "AVOIDABLE WASTE"])
    assert.match(journey, new RegExp(label))
})

test("the two profile names and non-color cues are visible in source", () => {
  const overlay = read("Overlay.qml")
  assert.match(overlay, /GREEN MONITOR/)
  assert.match(overlay, /COLOR DELUXE/)
  assert.match(overlay, /COLOR \[V\]/)
  assert.match(overlay, /ASSIST \[H\]/)
  assert.match(overlay, /PAUSE \[P\]/)
})

test("trail controls fit the scaled Omarchy viewport", () => {
  const journey = read("JourneyView.qml")
  const trail = read("TrailScene.qml")
  assert.match(journey, /height:\s*Math\.max\(160,\s*Math\.min\(270,\s*parent\.height\s*-\s*250\)\)/)
  assert.match(journey, /property real actionWidth:\s*\(width\s*-\s*spacing\s*\*\s*6\)\s*\/\s*7/)
  assert.equal((journey.match(/width:\s*parent\.actionWidth/g) || []).length, 7)
  assert.match(trail, /y:\s*Math\.max\(8,\s*root\.height\s*-\s*height\s*-\s*36\)/)
})
